name: Java CI with Maven

on:
  push:
    branches: [ $default-branch ]
    pull_request: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 (x64)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribtuion: 'temurin'
          architecture: x64
          cache: maven
      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots test
        working-directory: daisypass
